run: 
  databricks repos update "${{env.REPO PATH }}" \
    --branch "${{steps.extract_ branch.outputs.branch}}"

deploy-prod:
 needs: deploy-dev
 runs-on: ubuntu-latest 
 environment: production
 env:
   DATABRICKS_ HOST: ${{ secrets.PROD_DEPLOYMENT_TARGET_URL}}
   DATABRICKS_TOKEN: ${{ secrets.PROD_DEPLOYMENT_TARGET_ TOKEN }}
   REPO_PATH: <repo-path-from-databricks-workspace>

steps:
 -name: Checkout repository
  uses: actions/checkout@v3

 -name: Set up Python
  uses: actions/setup-python@v3
  with: python-version: 3.8

 -name: Set up Databricks CLI
  uses: databricks/setup-cli@main

 -name: Extract branch name
  id:   extract_branch_prod
  run: echo "branch=$(echo ${GITHUB_REF#refs/heads/})">> $GITHUB OUTPUT

 -name: Update Databricks Repo (Prod)
  run:
    databricks repos update "$(( env.REPO_PATH ))" \
   I --branch "${{ steps.extract_branch_prod.outputs.branch }}"
